server_url: 'http://96a77bd8.ngrok.io'
secret_key: ''
preview_entity_types:
  node: node
  block_content: 0
  comment: 0
  contact_message: 0
  file: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  menu_link_content: 0
incrementalbuild_url: 'http://96a77bd8.ngrok.io'
